trigger :
 branches:
   include:
     -  main
pr:
 branches:
   include:
     - main

pool:
 vmImage: ubuntu-latest

parameters:
  - name: environment
    type: string
    displayName: Select environment to provision infrastructure
    default: dev
    values:
      - dev
      - qa
      - staging
      - prod

stages:
  - stage: Init
    displayName: 'Terraform Init'
    jobs:
      - job: Init
        steps:
          - task: TerraformInstaller@2
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
          - task: TerraformCLI@0
            inputs:
              
              command: 'init'
              backendServiceArm: service_connection1
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              commandOptions: -upgrade -reconfigure -backend-config="environments/${{ parameters.environment }}/backend.config"

    
          
  - stage: Plan
    displayName: 'Terraform Plan'
    dependsOn: Init
    jobs:
    - job: Plan
      steps:
        - task: TerraformCLI@0
          inputs:
            
            command: 'plan'
            environmentServiceName: service_connection1
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            commandOptions: -var-file="environments/${{ parameters.environment }}/terraform.tfvars" -out=tfplan
  
  - stage: Apply
    displayName: 'Terraform Apply'
    dependsOn: Plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
    - job: Validation
      displayName: 'Wait for Approval'
      pool: server
      timeoutInMinutes: 4320 # 3 days
      steps:
        - task: ManualValidation@0
          inputs:
            instructions: 'Approve to deploy to $(parameters.environment)'
            onTimeout: 'reject'
    - job: Apply
      displayName: 'Terraform Apply'
      dependsOn: Validation
      steps:
        - task: TerraformCLI@0
          displayName: 'terraform apply'
          inputs:
            command: 'apply'
            environmentServiceName: service_connection1
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            commandOptions: -auto-approve -var-file="environments/${{ parameters.environment }}/terraform.tfvars"




          
            
    