apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nodejs-app-kv-integration
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    # userAssignedIdentityID: "3329d30a-51f9-4a0f-b3c0-666474c3c694"
    # userAssignedIdentityID: "/subscriptions/5cee968e-0ccf-40be-819c-34d922970b94/resourcegroups/MC_proj-dev-rg_proj-dev-aks_westus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-proj-dev-aks"
    userAssignedIdentityID: ${USER_ASSIGNED_ID}
    keyvaultName: ${key_vault_name}
    tenantId: b41b72d0-4e9f-4c26-8a69-f949f367c91d
    objects: |
      array:
        - |
          objectName: ${sql_admin_secret_name}
          objectType: secret
        - |
          objectName: ${sql_password_secret_name}
          objectType: secret
        - |
          objectName: ${sql_server_name}
          objectType: secret
        - |
          objectName: ${sql_db_name}
          objectType: secret
  secretObjects:
    - secretName: sql-secrets
      type: Opaque
      data:
        - objectName: ${sql_admin_secret_name}
          key: SQL_USER
        - objectName: ${sql_password_secret_name}
          key: SQL_PASSWORD
        - objectName: ${sql_server_name}
          key: SQL_SERVER
        - objectName: ${sql_db_name}
          key: SQL_DATABASE